export const dummyUsers = [
  {
    id: 1,
    name: "John Doe",
    age: 28,
    contactNumber: "123-456-7890",
    gmail: "john.doe@example.com",
    place: "New York",
    designation: "Software Engineer",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 34,
    contactNumber: "987-654-3210",
    gmail: "jane.smith@example.com",
    place: "Los Angeles",
    designation: "Product Manager",
  },
  {
    id: 3,
    name: "Michael Johnson",
    age: 25,
    contactNumber: "555-123-4567",
    gmail: "michael.johnson@example.com",
    place: "Chicago",
    designation: "UX Designer",
  },
  {
    id: 4,
    name: "Emily Davis",
    age: 29,
    contactNumber: "666-789-0123",
    gmail: "emily.davis@example.com",
    place: "Miami",
    designation: "Data Analyst",
  },
  {
    id: 5,
    name: "David Lee",
    age: 38,
    contactNumber: "777-654-8901",
    gmail: "david.lee@example.com",
    place: "San Francisco",
    designation: "Marketing Director",
  },
  {
    id: 6,
    name: "Sarah Wilson",
    age: 22,
    contactNumber: "888-234-5678",
    gmail: "sarah.wilson@example.com",
    place: "Seattle",
    designation: "Sales Associate",
  },
  {
    id: 7,
    name: "James Brown",
    age: 40,
    contactNumber: "999-345-6789",
    gmail: "james.brown@example.com",
    place: "Boston",
    designation: "HR Manager",
  },
  {
    id: 8,
    name: "Olivia Martinez",
    age: 26,
    contactNumber: "111-567-8901",
    gmail: "olivia.martinez@example.com",
    place: "Austin",
    designation: "Product Designer",
  },
  {
    id: 9,
    name: "William Taylor",
    age: 31,
    contactNumber: "222-678-9012",
    gmail: "william.taylor@example.com",
    place: "Denver",
    designation: "Software Developer",
  },
  {
    id: 10,
    name: "Sophia Anderson",
    age: 27,
    contactNumber: "333-789-0123",
    gmail: "sophia.anderson@example.com",
    place: "Dallas",
    designation: "Accountant",
  },
  {
    id: 11,
    name: "Benjamin Thomas",
    age: 33,
    contactNumber: "444-890-1234",
    gmail: "benjamin.thomas@example.com",
    place: "Portland",
    designation: "Operations Manager",
  },
  {
    id: 12,
    name: "Isabella Moore",
    age: 30,
    contactNumber: "555-901-2345",
    gmail: "isabella.moore@example.com",
    place: "San Diego",
    designation: "Business Analyst",
  },
  {
    id: 13,
    name: "Ethan White",
    age: 24,
    contactNumber: "666-012-3456",
    gmail: "ethan.white@example.com",
    place: "Atlanta",
    designation: "Graphic Designer",
  },
  {
    id: 14,
    name: "Charlotte Harris",
    age: 37,
    contactNumber: "777-123-4567",
    gmail: "charlotte.harris@example.com",
    place: "Houston",
    designation: "Finance Manager",
  },
  {
    id: 15,
    name: "Daniel Clark",
    age: 41,
    contactNumber: "888-234-5678",
    gmail: "daniel.clark@example.com",
    place: "Phoenix",
    designation: "Chief Executive Officer",
  },
  {
    id: 16,
    name: "Amelia Lewis",
    age: 28,
    contactNumber: "999-345-6789",
    gmail: "amelia.lewis@example.com",
    place: "New York",
    designation: "PR Specialist",
  },
  {
    id: 17,
    name: "Matthew Young",
    age: 35,
    contactNumber: "111-456-7890",
    gmail: "matthew.young@example.com",
    place: "Los Angeles",
    designation: "Business Development",
  },
  {
    id: 18,
    name: "Ava King",
    age: 32,
    contactNumber: "222-567-8901",
    gmail: "ava.king@example.com",
    place: "Chicago",
    designation: "Operations Analyst",
  },
  {
    id: 19,
    name: "Joshua Wright",
    age: 29,
    contactNumber: "333-678-9012",
    gmail: "joshua.wright@example.com",
    place: "Miami",
    designation: "Software Architect",
  },
  {
    id: 20,
    name: "Mia Scott",
    age: 30,
    contactNumber: "444-789-0123",
    gmail: "mia.scott@example.com",
    place: "San Francisco",
    designation: "Content Writer",
  },
  {
    id: 21,
    name: "Jameson Walker",
    age: 26,
    contactNumber: "555-890-1234",
    gmail: "jameson.walker@example.com",
    place: "Seattle",
    designation: "Business Consultant",
  },
  {
    id: 22,
    name: "Ella Green",
    age: 33,
    contactNumber: "666-901-2345",
    gmail: "ella.green@example.com",
    place: "Boston",
    designation: "Event Planner",
  },
  {
    id: 23,
    name: "Jackson Allen",
    age: 38,
    contactNumber: "777-012-3456",
    gmail: "jackson.allen@example.com",
    place: "Austin",
    designation: "Financial Analyst",
  },
  {
    id: 24,
    name: "Lily Perez",
    age: 41,
    contactNumber: "888-123-4567",
    gmail: "lily.perez@example.com",
    place: "Dallas",
    designation: "Marketing Specialist",
  },
  {
    id: 25,
    name: "Lucas Ramirez",
    age: 27,
    contactNumber: "999-234-5678",
    gmail: "lucas.ramirez@example.com",
    place: "Portland",
    designation: "SEO Expert",
  },
  {
    id: 26,
    name: "Mason Carter",
    age: 29,
    contactNumber: "111-345-6789",
    gmail: "mason.carter@example.com",
    place: "San Diego",
    designation: "Recruiter",
  },
  {
    id: 27,
    name: "Harper Mitchell",
    age: 34,
    contactNumber: "222-456-7890",
    gmail: "harper.mitchell@example.com",
    place: "Houston",
    designation: "UX Researcher",
  },
  {
    id: 28,
    name: "Logan Roberts",
    age: 26,
    contactNumber: "333-567-8901",
    gmail: "logan.roberts@example.com",
    place: "Phoenix",
    designation: "Software Tester",
  },
  {
    id: 29,
    name: "Scarlett Carter",
    age: 28,
    contactNumber: "444-678-9012",
    gmail: "scarlett.carter@example.com",
    place: "New York",
    designation: "Social Media Manager",
  },
  {
    id: 30,
    name: "Jack Adams",
    age: 36,
    contactNumber: "555-789-0123",
    gmail: "jack.adams@example.com",
    place: "Los Angeles",
    designation: "Web Developer",
  },
  {
    id: 31,
    name: "Chloe Nelson",
    age: 31,
    contactNumber: "666-890-1234",
    gmail: "chloe.nelson@example.com",
    place: "Chicago",
    designation: "IT Specialist",
  },
  {
    id: 32,
    name: "Wyatt Carter",
    age: 39,
    contactNumber: "777-901-2345",
    gmail: "wyatt.carter@example.com",
    place: "Miami",
    designation: "Sales Director",
  },
  {
    id: 33,
    name: "Zoe Evans",
    age: 23,
    contactNumber: "888-012-3456",
    gmail: "zoe.evans@example.com",
    place: "San Francisco",
    designation: "Junior Developer",
  },
  {
    id: 34,
    name: "Oliver Baker",
    age: 32,
    contactNumber: "999-123-4567",
    gmail: "oliver.baker@example.com",
    place: "Seattle",
    designation: "Creative Director",
  },
  {
    id: 35,
    name: "Grace Lee",
    age: 28,
    contactNumber: "111-234-5678",
    gmail: "grace.lee@example.com",
    place: "Boston",
    designation: "Content Strategist",
  },
  {
    id: 36,
    name: "Aiden Harris",
    age: 29,
    contactNumber: "222-345-6789",
    gmail: "aiden.harris@example.com",
    place: "Austin",
    designation: "Video Producer",
  },
  {
    id: 37,
    name: "Megan Clark",
    age: 30,
    contactNumber: "333-456-7890",
    gmail: "megan.clark@example.com",
    place: "Dallas",
    designation: "Operations Director",
  },
  {
    id: 38,
    name: "Matthew King",
    age: 41,
    contactNumber: "444-567-8901",
    gmail: "matthew.king@example.com",
    place: "Portland",
    designation: "Chief Marketing Officer",
  },
  {
    id: 39,
    name: "Liam Hall",
    age: 27,
    contactNumber: "555-678-9012",
    gmail: "liam.hall@example.com",
    place: "San Diego",
    designation: "Business Consultant",
  },
  {
    id: 40,
    name: "Nora Wright",
    age: 26,
    contactNumber: "666-789-0123",
    gmail: "nora.wright@example.com",
    place: "Houston",
    designation: "Project Manager",
  },
  {
    id: 41,
    name: "Samuel Evans",
    age: 33,
    contactNumber: "777-890-1234",
    gmail: "samuel.evans@example.com",
    place: "Phoenix",
    designation: "IT Director",
  },
  {
    id: 42,
    name: "Victoria Roberts",
    age: 36,
    contactNumber: "888-901-2345",
    gmail: "victoria.roberts@example.com",
    place: "New York",
    designation: "HR Specialist",
  },
  {
    id: 43,
    name: "Henry Adams",
    age: 31,
    contactNumber: "999-012-3456",
    gmail: "henry.adams@example.com",
    place: "Los Angeles",
    designation: "Product Owner",
  },
  {
    id: 44,
    name: "Sophie Taylor",
    age: 29,
    contactNumber: "111-345-6789",
    gmail: "sophie.taylor@example.com",
    place: "Chicago",
    designation: "Software Engineer",
  },
  {
    id: 45,
    name: "Daniel Miller",
    age: 38,
    contactNumber: "222-456-7890",
    gmail: "daniel.miller@example.com",
    place: "Miami",
    designation: "System Administrator",
  },
  {
    id: 46,
    name: "Luna Martinez",
    age: 27,
    contactNumber: "333-567-8901",
    gmail: "luna.martinez@example.com",
    place: "San Francisco",
    designation: "UI/UX Designer",
  },
  {
    id: 47,
    name: "Isaac Scott",
    age: 32,
    contactNumber: "444-678-9012",
    gmail: "isaac.scott@example.com",
    place: "Seattle",
    designation: "Data Scientist",
  },
  {
    id: 48,
    name: "Evelyn Taylor",
    age: 35,
    contactNumber: "555-789-0123",
    gmail: "evelyn.taylor@example.com",
    place: "Portland",
    designation: "Business Consultant",
  },
  {
    id: 49,
    name: "Noah White",
    age: 24,
    contactNumber: "666-890-1234",
    gmail: "noah.white@example.com",
    place: "Dallas",
    designation: "Cloud Architect",
  },
  {
    id: 50,
    name: "Mila Perez",
    age: 28,
    contactNumber: "777-901-2345",
    gmail: "mila.perez@example.com",
    place: "Boston",
    designation: "Product Designer",
  },
];
